# Site settings
title: HackcessibleMap - DSSG Sidewalk Team 2015
email: yunhao.lucky@gmail.com
description: "Best Routing Application for people with limited mobilities in Seattle"
baseurl: "http://uwescience.github.io/DSSG2015"
url: "http://uwescience.github.io/DSSG2015"
twitter_username: uwescience
github_username:  uwescience


# Build settings
markdown: kramdown
